#ifndef SOURCEMETA_ONE_RULES_H_
#define SOURCEMETA_ONE_RULES_H_

#include <sourcemeta/one/build.h>

namespace sourcemeta::one {

enum : BuildPlan::Action::Type {
  ACTION_MATERIALISE,
  ACTION_POSITIONS,
  ACTION_LOCATIONS,
  ACTION_DEPENDENCIES,
  ACTION_STATS,
  ACTION_HEALTH,
  ACTION_BUNDLE,
  ACTION_EDITOR,
  ACTION_BLAZE_EXHAUSTIVE,
  ACTION_BLAZE_FAST,
  ACTION_SCHEMA_METADATA,
  ACTION_DEPENDENTS,
  ACTION_SEARCH_INDEX,
  ACTION_MCP,
  ACTION_DIRECTORY_LIST,
  ACTION_WEB_INDEX,
  ACTION_WEB_NOT_FOUND,
  ACTION_WEB_DIRECTORY,
  ACTION_WEB_SCHEMA,
  ACTION_COMMENT,
  ACTION_CONFIGURATION,
  ACTION_VERSION,
  ACTION_ROUTES,
  ACTION_AUTHENTICATION,
  ACTION_WEB_UNAUTHORIZED,
  ACTION_REMOVE,
  ACTION_COUNT
};

enum : BuildPlan::Type { MODE_HEADLESS, MODE_FULL };

inline constexpr DeltaRuleSet<13, 7, 5, 2> INDEX_RULES{
    .leaves = {{
        {.action = ACTION_MATERIALISE,
         .base = 0,
         .filename = "schema.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = true,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::ExternalSource,
                            .base = 0,
                            .filename = nullptr},
                           {.source = DependencySource::ExternalConfig,
                            .base = 0,
                            .filename = nullptr}}},
         .dependency_count = 2},

        {.action = ACTION_POSITIONS,
         .base = 0,
         .filename = "positions.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_LOCATIONS,
         .base = 0,
         .filename = "locations.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_DEPENDENCIES,
         .base = 0,
         .filename = "dependencies.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = true,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"},
                           {.source = DependencySource::GlobalOutput,
                            .base = 0,
                            .filename = "authentication.bin"}}},
         .dependency_count = 2},

        {.action = ACTION_STATS,
         .base = 0,
         .filename = "stats.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_HEALTH,
         .base = 0,
         .filename = "health.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "dependencies.metapack"}}},
         .dependency_count = 2},

        {.action = ACTION_BUNDLE,
         .base = 0,
         .filename = "bundle.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "dependencies.metapack"}}},
         .dependency_count = 2},

        {.action = ACTION_EDITOR,
         .base = 0,
         .filename = "editor.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "bundle.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_BLAZE_EXHAUSTIVE,
         .base = 0,
         .filename = "blaze-exhaustive.metapack",
         .gate = TargetGate::IfEvaluate,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "bundle.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_BLAZE_FAST,
         .base = 0,
         .filename = "blaze-fast.metapack",
         .gate = TargetGate::IfEvaluate,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "bundle.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_SCHEMA_METADATA,
         .base = 1,
         .filename = "schema.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = true,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "schema.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "health.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "dependencies.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "bundle.metapack"}}},
         .dependency_count = 4},

        {.action = ACTION_DEPENDENTS,
         .base = 0,
         .filename = "dependents.metapack",
         .gate = TargetGate::Always,
         .dirty = DirtyOverride::ForceOnGraphChange,
         .is_root = false,
         .combine_only = true,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 0,
                            .filename = "dependencies.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_WEB_SCHEMA,
         .base = 1,
         .filename = "schema-html.metapack",
         .gate = TargetGate::OnlyInFullMode,
         .dirty = DirtyOverride::Normal,
         .is_root = false,
         .combine_only = false,
         .container_target = false,
         .tracks_dependencies = false,
         .dependencies = {{{.source = DependencySource::Base,
                            .base = 1,
                            .filename = "schema.metapack"},
                           {.source = DependencySource::Base,
                            .base = 0,
                            .filename = "health.metapack"}}},
         .dependency_count = 2},
    }},
    .containers = {{
        {.action = ACTION_DIRECTORY_LIST,
         .base = 1,
         .filename = "directory.metapack",
         .gate = TargetGate::Always,
         .scope = ContainerScope::AllContainers,
         .only_full_rebuild = false,
         .is_listing = true,
         .dependencies = {{{.kind = ContainerDependencyKind::LeafMetadata,
                            .filename = nullptr},
                           {.kind = ContainerDependencyKind::ChildContainers,
                            .filename = nullptr}}},
         .dependency_count = 2},

        {.action = ACTION_SEARCH_INDEX,
         .base = 1,
         .filename = "search.metapack",
         .gate = TargetGate::Always,
         .scope = ContainerScope::RootOnly,
         .only_full_rebuild = false,
         .is_listing = false,
         .dependencies = {{{.kind =
                                ContainerDependencyKind::AllContainerListings,
                            .filename = nullptr}}},
         .dependency_count = 1},

        {.action = ACTION_MCP,
         .base = 1,
         .filename = "mcp.metapack",
         .gate = TargetGate::Always,
         .scope = ContainerScope::RootOnly,
         .only_full_rebuild = false,
         .is_listing = false,
         .dependencies =
             {{{.kind = ContainerDependencyKind::SameContainerTarget,
                .filename = "search.metapack"},
               {.kind = ContainerDependencyKind::ExternalConfig,
                .filename = nullptr},
               {.kind = ContainerDependencyKind::Global, .filename = nullptr}}},
         .dependency_count = 3},

        {.action = ACTION_WEB_INDEX,
         .base = 1,
         .filename = "directory-html.metapack",
         .gate = TargetGate::OnlyInFullMode,
         .scope = ContainerScope::RootOnly,
         .only_full_rebuild = false,
         .is_listing = false,
         .dependencies = {{{.kind =
                                ContainerDependencyKind::SameContainerTarget,
                            .filename = "directory.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_WEB_DIRECTORY,
         .base = 1,
         .filename = "directory-html.metapack",
         .gate = TargetGate::OnlyInFullMode,
         .scope = ContainerScope::NonRoot,
         .only_full_rebuild = false,
         .is_listing = false,
         .dependencies = {{{.kind =
                                ContainerDependencyKind::SameContainerTarget,
                            .filename = "directory.metapack"}}},
         .dependency_count = 1},

        {.action = ACTION_WEB_NOT_FOUND,
         .base = 1,
         .filename = "404.metapack",
         .gate = TargetGate::OnlyInFullMode,
         .scope = ContainerScope::RootOnly,
         .only_full_rebuild = true,
         .is_listing = false,
         .dependencies = {{{.kind = ContainerDependencyKind::ExternalConfig,
                            .filename = nullptr}}},
         .dependency_count = 1},

        {.action = ACTION_WEB_UNAUTHORIZED,
         .base = 1,
         .filename = "401.metapack",
         .gate = TargetGate::OnlyInFullMode,
         .scope = ContainerScope::RootOnly,
         .only_full_rebuild = true,
         .is_listing = false,
         .dependencies = {{{.kind = ContainerDependencyKind::ExternalConfig,
                            .filename = nullptr}}},
         .dependency_count = 1},
    }},
    .globals = {{
        {.action = ACTION_VERSION,
         .filename = "version.json",
         .trigger = GlobalTrigger::WithVersion,
         .external_config_anchor = false,
         .dependencies = {},
         .dependency_count = 0},
        {.action = ACTION_CONFIGURATION,
         .filename = "configuration.json",
         .trigger = GlobalTrigger::FullRebuild,
         .external_config_anchor = true,
         .dependencies = {},
         .dependency_count = 0},
        {.action = ACTION_COMMENT,
         .filename = "comment.json",
         .trigger = GlobalTrigger::WithComment,
         .external_config_anchor = false,
         .dependencies = {},
         .dependency_count = 0},
        {.action = ACTION_ROUTES,
         .filename = "routes.bin",
         .trigger = GlobalTrigger::OnModeChange,
         .external_config_anchor = false,
         .dependencies = {},
         .dependency_count = 0},
        {.action = ACTION_AUTHENTICATION,
         .filename = "authentication.bin",
         .trigger = GlobalTrigger::FullRebuild,
         .external_config_anchor = false,
         .dependencies = {{{.source = DependencySource::GlobalOutput,
                            .base = 0,
                            .filename = "routes.bin"}}},
         .dependency_count = 1},
    }},
    .directories = {{"schemas", "explorer"}},
    .sentinel = "%",
    .remove_action = ACTION_REMOVE,
    .full_mode = MODE_FULL,
};

} // namespace sourcemeta::one

#endif
