services:
  sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SOURCEMETA_ONE_PORT=8000
      - ONE_E2E_VAULT_KEY=vault-secret-key
    ports:
      - "${PORT}:8000"
