#!/bin/sh

set -o errexit
set -o nounset

TMP="$(mktemp -d)"
clean() { rm -rf "$TMP"; }
trap clean EXIT

mkdir "$TMP/schemas"

cat << 'EOF' > "$TMP/schemas/test.json"
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/%25/test"
}
EOF

cat << EOF > "$TMP/one.json"
{
  "url": "http://localhost:8000",
  "html": false,
  "contents": {
    "example": {
      "baseUri": "https://example.com",
      "path": "./schemas"
    }
  }
}
EOF

"$1" "$TMP/one.json" "$TMP/output"

cd "$TMP/output"
find . -mindepth 1 | LC_ALL=C sort > "$TMP/manifest.txt"
cd - > /dev/null

cat << 'EOF' > "$TMP/expected.txt"
./configuration.json
./explorer
./explorer/%
./explorer/%/directory.metapack
./explorer/%/mcp.metapack
./explorer/%/search.metapack
./explorer/example
./explorer/example/%
./explorer/example/%/directory.metapack
./explorer/example/%25
./explorer/example/%25/%
./explorer/example/%25/%/directory.metapack
./explorer/example/%25/test
./explorer/example/%25/test/%
./explorer/example/%25/test/%/schema.metapack
./explorer/self
./explorer/self/%
./explorer/self/%/directory.metapack
./explorer/self/v1
./explorer/self/v1/%
./explorer/self/v1/%/directory.metapack
./explorer/self/v1/schemas
./explorer/self/v1/schemas/%
./explorer/self/v1/schemas/%/directory.metapack
./explorer/self/v1/schemas/api
./explorer/self/v1/schemas/api/%
./explorer/self/v1/schemas/api/%/directory.metapack
./explorer/self/v1/schemas/api/error
./explorer/self/v1/schemas/api/error/%
./explorer/self/v1/schemas/api/error/%/schema.metapack
./explorer/self/v1/schemas/api/list
./explorer/self/v1/schemas/api/list/%
./explorer/self/v1/schemas/api/list/%/directory.metapack
./explorer/self/v1/schemas/api/list/response
./explorer/self/v1/schemas/api/list/response/%
./explorer/self/v1/schemas/api/list/response/%/schema.metapack
./explorer/self/v1/schemas/api/list/rpc
./explorer/self/v1/schemas/api/list/rpc/%
./explorer/self/v1/schemas/api/list/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas
./explorer/self/v1/schemas/api/schemas/%
./explorer/self/v1/schemas/api/schemas/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependencies
./explorer/self/v1/schemas/api/schemas/dependencies/%
./explorer/self/v1/schemas/api/schemas/dependencies/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/response
./explorer/self/v1/schemas/api/schemas/dependencies/response/%
./explorer/self/v1/schemas/api/schemas/dependencies/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/%
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependents
./explorer/self/v1/schemas/api/schemas/dependents/%
./explorer/self/v1/schemas/api/schemas/dependents/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependents/response
./explorer/self/v1/schemas/api/schemas/dependents/response/%
./explorer/self/v1/schemas/api/schemas/dependents/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc
./explorer/self/v1/schemas/api/schemas/dependents/rpc/%
./explorer/self/v1/schemas/api/schemas/dependents/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate
./explorer/self/v1/schemas/api/schemas/evaluate/%
./explorer/self/v1/schemas/api/schemas/evaluate/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/request
./explorer/self/v1/schemas/api/schemas/evaluate/request/%
./explorer/self/v1/schemas/api/schemas/evaluate/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/response
./explorer/self/v1/schemas/api/schemas/evaluate/response/%
./explorer/self/v1/schemas/api/schemas/evaluate/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/%
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/health
./explorer/self/v1/schemas/api/schemas/health/%
./explorer/self/v1/schemas/api/schemas/health/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/health/response
./explorer/self/v1/schemas/api/schemas/health/response/%
./explorer/self/v1/schemas/api/schemas/health/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc
./explorer/self/v1/schemas/api/schemas/health/rpc/%
./explorer/self/v1/schemas/api/schemas/health/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/locations
./explorer/self/v1/schemas/api/schemas/locations/%
./explorer/self/v1/schemas/api/schemas/locations/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/locations/response
./explorer/self/v1/schemas/api/schemas/locations/response/%
./explorer/self/v1/schemas/api/schemas/locations/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc
./explorer/self/v1/schemas/api/schemas/locations/rpc/%
./explorer/self/v1/schemas/api/schemas/locations/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/metadata
./explorer/self/v1/schemas/api/schemas/metadata/%
./explorer/self/v1/schemas/api/schemas/metadata/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/metadata/response
./explorer/self/v1/schemas/api/schemas/metadata/response/%
./explorer/self/v1/schemas/api/schemas/metadata/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc
./explorer/self/v1/schemas/api/schemas/metadata/rpc/%
./explorer/self/v1/schemas/api/schemas/metadata/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/position
./explorer/self/v1/schemas/api/schemas/position/%
./explorer/self/v1/schemas/api/schemas/position/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/positions
./explorer/self/v1/schemas/api/schemas/positions/%
./explorer/self/v1/schemas/api/schemas/positions/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/positions/response
./explorer/self/v1/schemas/api/schemas/positions/response/%
./explorer/self/v1/schemas/api/schemas/positions/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc
./explorer/self/v1/schemas/api/schemas/positions/rpc/%
./explorer/self/v1/schemas/api/schemas/positions/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/search
./explorer/self/v1/schemas/api/schemas/search/%
./explorer/self/v1/schemas/api/schemas/search/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/search/response
./explorer/self/v1/schemas/api/schemas/search/response/%
./explorer/self/v1/schemas/api/schemas/search/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc
./explorer/self/v1/schemas/api/schemas/search/rpc/%
./explorer/self/v1/schemas/api/schemas/search/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/stats
./explorer/self/v1/schemas/api/schemas/stats/%
./explorer/self/v1/schemas/api/schemas/stats/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/stats/response
./explorer/self/v1/schemas/api/schemas/stats/response/%
./explorer/self/v1/schemas/api/schemas/stats/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc
./explorer/self/v1/schemas/api/schemas/stats/rpc/%
./explorer/self/v1/schemas/api/schemas/stats/rpc/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace
./explorer/self/v1/schemas/api/schemas/trace/%
./explorer/self/v1/schemas/api/schemas/trace/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/trace/request
./explorer/self/v1/schemas/api/schemas/trace/request/%
./explorer/self/v1/schemas/api/schemas/trace/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace/response
./explorer/self/v1/schemas/api/schemas/trace/response/%
./explorer/self/v1/schemas/api/schemas/trace/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc
./explorer/self/v1/schemas/api/schemas/trace/rpc/%
./explorer/self/v1/schemas/api/schemas/trace/rpc/%/schema.metapack
./explorer/self/v1/schemas/mcp
./explorer/self/v1/schemas/mcp/%
./explorer/self/v1/schemas/mcp/%/directory.metapack
./explorer/self/v1/schemas/mcp/error
./explorer/self/v1/schemas/mcp/error/%
./explorer/self/v1/schemas/mcp/error/%/schema.metapack
./explorer/self/v1/schemas/mcp/initialize
./explorer/self/v1/schemas/mcp/initialize/%
./explorer/self/v1/schemas/mcp/initialize/%/directory.metapack
./explorer/self/v1/schemas/mcp/initialize/request
./explorer/self/v1/schemas/mcp/initialize/request/%
./explorer/self/v1/schemas/mcp/initialize/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/initialize/response
./explorer/self/v1/schemas/mcp/initialize/response/%
./explorer/self/v1/schemas/mcp/initialize/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/notifications
./explorer/self/v1/schemas/mcp/notifications/%
./explorer/self/v1/schemas/mcp/notifications/%/directory.metapack
./explorer/self/v1/schemas/mcp/notifications/cancelled
./explorer/self/v1/schemas/mcp/notifications/cancelled/%
./explorer/self/v1/schemas/mcp/notifications/cancelled/%/schema.metapack
./explorer/self/v1/schemas/mcp/notifications/initialized
./explorer/self/v1/schemas/mcp/notifications/initialized/%
./explorer/self/v1/schemas/mcp/notifications/initialized/%/schema.metapack
./explorer/self/v1/schemas/mcp/ping
./explorer/self/v1/schemas/mcp/ping/%
./explorer/self/v1/schemas/mcp/ping/%/directory.metapack
./explorer/self/v1/schemas/mcp/ping/request
./explorer/self/v1/schemas/mcp/ping/request/%
./explorer/self/v1/schemas/mcp/ping/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/ping/response
./explorer/self/v1/schemas/mcp/ping/response/%
./explorer/self/v1/schemas/mcp/ping/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/request
./explorer/self/v1/schemas/mcp/request/%
./explorer/self/v1/schemas/mcp/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources
./explorer/self/v1/schemas/mcp/resources/%
./explorer/self/v1/schemas/mcp/resources/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/list
./explorer/self/v1/schemas/mcp/resources/list/%
./explorer/self/v1/schemas/mcp/resources/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/list/request
./explorer/self/v1/schemas/mcp/resources/list/request/%
./explorer/self/v1/schemas/mcp/resources/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/list/response
./explorer/self/v1/schemas/mcp/resources/list/response/%
./explorer/self/v1/schemas/mcp/resources/list/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/read
./explorer/self/v1/schemas/mcp/resources/read/%
./explorer/self/v1/schemas/mcp/resources/read/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/read/request
./explorer/self/v1/schemas/mcp/resources/read/request/%
./explorer/self/v1/schemas/mcp/resources/read/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/read/response
./explorer/self/v1/schemas/mcp/resources/read/response/%
./explorer/self/v1/schemas/mcp/resources/read/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/templates
./explorer/self/v1/schemas/mcp/resources/templates/%
./explorer/self/v1/schemas/mcp/resources/templates/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list
./explorer/self/v1/schemas/mcp/resources/templates/list/%
./explorer/self/v1/schemas/mcp/resources/templates/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/request
./explorer/self/v1/schemas/mcp/resources/templates/list/request/%
./explorer/self/v1/schemas/mcp/resources/templates/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/response
./explorer/self/v1/schemas/mcp/resources/templates/list/response/%
./explorer/self/v1/schemas/mcp/resources/templates/list/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/response
./explorer/self/v1/schemas/mcp/response/%
./explorer/self/v1/schemas/mcp/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools
./explorer/self/v1/schemas/mcp/tools/%
./explorer/self/v1/schemas/mcp/tools/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/call
./explorer/self/v1/schemas/mcp/tools/call/%
./explorer/self/v1/schemas/mcp/tools/call/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/call/request
./explorer/self/v1/schemas/mcp/tools/call/request/%
./explorer/self/v1/schemas/mcp/tools/call/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/call/response
./explorer/self/v1/schemas/mcp/tools/call/response/%
./explorer/self/v1/schemas/mcp/tools/call/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/list
./explorer/self/v1/schemas/mcp/tools/list/%
./explorer/self/v1/schemas/mcp/tools/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/list/request
./explorer/self/v1/schemas/mcp/tools/list/request/%
./explorer/self/v1/schemas/mcp/tools/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/list/response
./explorer/self/v1/schemas/mcp/tools/list/response/%
./explorer/self/v1/schemas/mcp/tools/list/response/%/schema.metapack
./routes.bin
./schemas
./schemas/example
./schemas/example/%25
./schemas/example/%25/test
./schemas/example/%25/test/%
./schemas/example/%25/test/%/blaze-exhaustive.metapack
./schemas/example/%25/test/%/blaze-fast.metapack
./schemas/example/%25/test/%/bundle.metapack
./schemas/example/%25/test/%/dependencies.metapack
./schemas/example/%25/test/%/dependents.metapack
./schemas/example/%25/test/%/editor.metapack
./schemas/example/%25/test/%/health.metapack
./schemas/example/%25/test/%/locations.metapack
./schemas/example/%25/test/%/positions.metapack
./schemas/example/%25/test/%/schema.metapack
./schemas/example/%25/test/%/stats.metapack
./schemas/self
./schemas/self/v1
./schemas/self/v1/schemas
./schemas/self/v1/schemas/api
./schemas/self/v1/schemas/api/error
./schemas/self/v1/schemas/api/error/%
./schemas/self/v1/schemas/api/error/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/error/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/error/%/bundle.metapack
./schemas/self/v1/schemas/api/error/%/dependencies.metapack
./schemas/self/v1/schemas/api/error/%/dependents.metapack
./schemas/self/v1/schemas/api/error/%/editor.metapack
./schemas/self/v1/schemas/api/error/%/health.metapack
./schemas/self/v1/schemas/api/error/%/locations.metapack
./schemas/self/v1/schemas/api/error/%/positions.metapack
./schemas/self/v1/schemas/api/error/%/schema.metapack
./schemas/self/v1/schemas/api/error/%/stats.metapack
./schemas/self/v1/schemas/api/list
./schemas/self/v1/schemas/api/list/response
./schemas/self/v1/schemas/api/list/response/%
./schemas/self/v1/schemas/api/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/list/response/%/bundle.metapack
./schemas/self/v1/schemas/api/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/list/response/%/dependents.metapack
./schemas/self/v1/schemas/api/list/response/%/editor.metapack
./schemas/self/v1/schemas/api/list/response/%/health.metapack
./schemas/self/v1/schemas/api/list/response/%/locations.metapack
./schemas/self/v1/schemas/api/list/response/%/positions.metapack
./schemas/self/v1/schemas/api/list/response/%/schema.metapack
./schemas/self/v1/schemas/api/list/response/%/stats.metapack
./schemas/self/v1/schemas/api/list/rpc
./schemas/self/v1/schemas/api/list/rpc/%
./schemas/self/v1/schemas/api/list/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/list/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/list/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/list/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/list/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/list/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/list/rpc/%/health.metapack
./schemas/self/v1/schemas/api/list/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/list/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/list/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/list/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas
./schemas/self/v1/schemas/api/schemas/dependencies
./schemas/self/v1/schemas/api/schemas/dependencies/response
./schemas/self/v1/schemas/api/schemas/dependencies/response/%
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependents
./schemas/self/v1/schemas/api/schemas/dependents/response
./schemas/self/v1/schemas/api/schemas/dependents/response/%
./schemas/self/v1/schemas/api/schemas/dependents/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate
./schemas/self/v1/schemas/api/schemas/evaluate/request
./schemas/self/v1/schemas/api/schemas/evaluate/request/%
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response
./schemas/self/v1/schemas/api/schemas/evaluate/response/%
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/health
./schemas/self/v1/schemas/api/schemas/health/response
./schemas/self/v1/schemas/api/schemas/health/response/%
./schemas/self/v1/schemas/api/schemas/health/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc
./schemas/self/v1/schemas/api/schemas/health/rpc/%
./schemas/self/v1/schemas/api/schemas/health/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/locations
./schemas/self/v1/schemas/api/schemas/locations/response
./schemas/self/v1/schemas/api/schemas/locations/response/%
./schemas/self/v1/schemas/api/schemas/locations/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc
./schemas/self/v1/schemas/api/schemas/locations/rpc/%
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/metadata
./schemas/self/v1/schemas/api/schemas/metadata/response
./schemas/self/v1/schemas/api/schemas/metadata/response/%
./schemas/self/v1/schemas/api/schemas/metadata/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/position
./schemas/self/v1/schemas/api/schemas/position/%
./schemas/self/v1/schemas/api/schemas/position/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/position/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/position/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/position/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/position/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/position/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/position/%/health.metapack
./schemas/self/v1/schemas/api/schemas/position/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/position/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/position/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/position/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/positions
./schemas/self/v1/schemas/api/schemas/positions/response
./schemas/self/v1/schemas/api/schemas/positions/response/%
./schemas/self/v1/schemas/api/schemas/positions/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc
./schemas/self/v1/schemas/api/schemas/positions/rpc/%
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/search
./schemas/self/v1/schemas/api/schemas/search/response
./schemas/self/v1/schemas/api/schemas/search/response/%
./schemas/self/v1/schemas/api/schemas/search/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc
./schemas/self/v1/schemas/api/schemas/search/rpc/%
./schemas/self/v1/schemas/api/schemas/search/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/stats
./schemas/self/v1/schemas/api/schemas/stats/response
./schemas/self/v1/schemas/api/schemas/stats/response/%
./schemas/self/v1/schemas/api/schemas/stats/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc
./schemas/self/v1/schemas/api/schemas/stats/rpc/%
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace
./schemas/self/v1/schemas/api/schemas/trace/request
./schemas/self/v1/schemas/api/schemas/trace/request/%
./schemas/self/v1/schemas/api/schemas/trace/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace/response
./schemas/self/v1/schemas/api/schemas/trace/response/%
./schemas/self/v1/schemas/api/schemas/trace/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc
./schemas/self/v1/schemas/api/schemas/trace/rpc/%
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/%/stats.metapack
./schemas/self/v1/schemas/mcp
./schemas/self/v1/schemas/mcp/error
./schemas/self/v1/schemas/mcp/error/%
./schemas/self/v1/schemas/mcp/error/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/error/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/error/%/bundle.metapack
./schemas/self/v1/schemas/mcp/error/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/error/%/dependents.metapack
./schemas/self/v1/schemas/mcp/error/%/editor.metapack
./schemas/self/v1/schemas/mcp/error/%/health.metapack
./schemas/self/v1/schemas/mcp/error/%/locations.metapack
./schemas/self/v1/schemas/mcp/error/%/positions.metapack
./schemas/self/v1/schemas/mcp/error/%/schema.metapack
./schemas/self/v1/schemas/mcp/error/%/stats.metapack
./schemas/self/v1/schemas/mcp/initialize
./schemas/self/v1/schemas/mcp/initialize/request
./schemas/self/v1/schemas/mcp/initialize/request/%
./schemas/self/v1/schemas/mcp/initialize/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/health.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/initialize/response
./schemas/self/v1/schemas/mcp/initialize/response/%
./schemas/self/v1/schemas/mcp/initialize/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/health.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/notifications
./schemas/self/v1/schemas/mcp/notifications/cancelled
./schemas/self/v1/schemas/mcp/notifications/cancelled/%
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/bundle.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/dependents.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/editor.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/health.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/locations.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/positions.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/schema.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/stats.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized
./schemas/self/v1/schemas/mcp/notifications/initialized/%
./schemas/self/v1/schemas/mcp/notifications/initialized/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/bundle.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/dependents.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/editor.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/health.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/locations.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/positions.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/schema.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/stats.metapack
./schemas/self/v1/schemas/mcp/ping
./schemas/self/v1/schemas/mcp/ping/request
./schemas/self/v1/schemas/mcp/ping/request/%
./schemas/self/v1/schemas/mcp/ping/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/health.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/ping/response
./schemas/self/v1/schemas/mcp/ping/response/%
./schemas/self/v1/schemas/mcp/ping/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/health.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/request
./schemas/self/v1/schemas/mcp/request/%
./schemas/self/v1/schemas/mcp/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/request/%/health.metapack
./schemas/self/v1/schemas/mcp/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources
./schemas/self/v1/schemas/mcp/resources/list
./schemas/self/v1/schemas/mcp/resources/list/request
./schemas/self/v1/schemas/mcp/resources/list/request/%
./schemas/self/v1/schemas/mcp/resources/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/list/response
./schemas/self/v1/schemas/mcp/resources/list/response/%
./schemas/self/v1/schemas/mcp/resources/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/read
./schemas/self/v1/schemas/mcp/resources/read/request
./schemas/self/v1/schemas/mcp/resources/read/request/%
./schemas/self/v1/schemas/mcp/resources/read/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/read/response
./schemas/self/v1/schemas/mcp/resources/read/response/%
./schemas/self/v1/schemas/mcp/resources/read/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/templates
./schemas/self/v1/schemas/mcp/resources/templates/list
./schemas/self/v1/schemas/mcp/resources/templates/list/request
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/response
./schemas/self/v1/schemas/mcp/response/%
./schemas/self/v1/schemas/mcp/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/response/%/health.metapack
./schemas/self/v1/schemas/mcp/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools
./schemas/self/v1/schemas/mcp/tools/call
./schemas/self/v1/schemas/mcp/tools/call/request
./schemas/self/v1/schemas/mcp/tools/call/request/%
./schemas/self/v1/schemas/mcp/tools/call/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/call/response
./schemas/self/v1/schemas/mcp/tools/call/response/%
./schemas/self/v1/schemas/mcp/tools/call/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/list
./schemas/self/v1/schemas/mcp/tools/list/request
./schemas/self/v1/schemas/mcp/tools/list/request/%
./schemas/self/v1/schemas/mcp/tools/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/list/response
./schemas/self/v1/schemas/mcp/tools/list/response/%
./schemas/self/v1/schemas/mcp/tools/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/stats.metapack
./state.bin
./version.json
EOF

diff "$TMP/manifest.txt" "$TMP/expected.txt"
