#!/bin/sh

set -o errexit
set -o nounset

TMP="$(mktemp -d)"
clean() { rm -rf "$TMP"; }
trap clean EXIT

cat << EOF > "$TMP/one.json"
{
  "url": "https://example.com/schemas/",
  "contents": {
    "example": {
      "baseUri": "https://example.com",
      "path": "./schemas"
    }
  }
}
EOF

mkdir "$TMP/schemas"

cat << 'EOF' > "$TMP/schemas/foo.json"
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/foo",
  "type": "string"
}
EOF

"$1" "$TMP/one.json" "$TMP/output"

cd "$TMP/output"
find . -mindepth 1 | LC_ALL=C sort > "$TMP/manifest.txt"
cd - > /dev/null

cat << 'EOF' > "$TMP/expected.txt"
./configuration.json
./explorer
./explorer/%
./explorer/%/404.metapack
./explorer/%/directory-html.metapack
./explorer/%/directory.metapack
./explorer/%/mcp.metapack
./explorer/%/search.metapack
./explorer/example
./explorer/example/%
./explorer/example/%/directory-html.metapack
./explorer/example/%/directory.metapack
./explorer/example/foo
./explorer/example/foo/%
./explorer/example/foo/%/schema-html.metapack
./explorer/example/foo/%/schema.metapack
./explorer/self
./explorer/self/%
./explorer/self/%/directory-html.metapack
./explorer/self/%/directory.metapack
./explorer/self/v1
./explorer/self/v1/%
./explorer/self/v1/%/directory-html.metapack
./explorer/self/v1/%/directory.metapack
./explorer/self/v1/schemas
./explorer/self/v1/schemas/%
./explorer/self/v1/schemas/%/directory-html.metapack
./explorer/self/v1/schemas/%/directory.metapack
./explorer/self/v1/schemas/api
./explorer/self/v1/schemas/api/%
./explorer/self/v1/schemas/api/%/directory-html.metapack
./explorer/self/v1/schemas/api/%/directory.metapack
./explorer/self/v1/schemas/api/error
./explorer/self/v1/schemas/api/error/%
./explorer/self/v1/schemas/api/error/%/schema-html.metapack
./explorer/self/v1/schemas/api/error/%/schema.metapack
./explorer/self/v1/schemas/api/list
./explorer/self/v1/schemas/api/list/%
./explorer/self/v1/schemas/api/list/%/directory-html.metapack
./explorer/self/v1/schemas/api/list/%/directory.metapack
./explorer/self/v1/schemas/api/list/response
./explorer/self/v1/schemas/api/list/response/%
./explorer/self/v1/schemas/api/list/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/list/response/%/schema.metapack
./explorer/self/v1/schemas/api/list/rpc
./explorer/self/v1/schemas/api/list/rpc/%
./explorer/self/v1/schemas/api/list/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/list/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/list/rpc/request
./explorer/self/v1/schemas/api/list/rpc/request/%
./explorer/self/v1/schemas/api/list/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/list/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/list/rpc/response
./explorer/self/v1/schemas/api/list/rpc/response/%
./explorer/self/v1/schemas/api/list/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/list/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas
./explorer/self/v1/schemas/api/schemas/%
./explorer/self/v1/schemas/api/schemas/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependencies
./explorer/self/v1/schemas/api/schemas/dependencies/%
./explorer/self/v1/schemas/api/schemas/dependencies/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/response
./explorer/self/v1/schemas/api/schemas/dependencies/response/%
./explorer/self/v1/schemas/api/schemas/dependencies/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/%
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/request
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/request/%
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/response
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/response/%
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependencies/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependents
./explorer/self/v1/schemas/api/schemas/dependents/%
./explorer/self/v1/schemas/api/schemas/dependents/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/dependents/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependents/response
./explorer/self/v1/schemas/api/schemas/dependents/response/%
./explorer/self/v1/schemas/api/schemas/dependents/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependents/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc
./explorer/self/v1/schemas/api/schemas/dependents/rpc/%
./explorer/self/v1/schemas/api/schemas/dependents/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc/request
./explorer/self/v1/schemas/api/schemas/dependents/rpc/request/%
./explorer/self/v1/schemas/api/schemas/dependents/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc/response
./explorer/self/v1/schemas/api/schemas/dependents/rpc/response/%
./explorer/self/v1/schemas/api/schemas/dependents/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/dependents/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate
./explorer/self/v1/schemas/api/schemas/evaluate/%
./explorer/self/v1/schemas/api/schemas/evaluate/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/request
./explorer/self/v1/schemas/api/schemas/evaluate/request/%
./explorer/self/v1/schemas/api/schemas/evaluate/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/response
./explorer/self/v1/schemas/api/schemas/evaluate/response/%
./explorer/self/v1/schemas/api/schemas/evaluate/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/%
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/request
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/request/%
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/response
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/response/%
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/evaluate/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/health
./explorer/self/v1/schemas/api/schemas/health/%
./explorer/self/v1/schemas/api/schemas/health/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/health/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/health/response
./explorer/self/v1/schemas/api/schemas/health/response/%
./explorer/self/v1/schemas/api/schemas/health/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/health/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc
./explorer/self/v1/schemas/api/schemas/health/rpc/%
./explorer/self/v1/schemas/api/schemas/health/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc/request
./explorer/self/v1/schemas/api/schemas/health/rpc/request/%
./explorer/self/v1/schemas/api/schemas/health/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc/response
./explorer/self/v1/schemas/api/schemas/health/rpc/response/%
./explorer/self/v1/schemas/api/schemas/health/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/health/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/locations
./explorer/self/v1/schemas/api/schemas/locations/%
./explorer/self/v1/schemas/api/schemas/locations/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/locations/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/locations/response
./explorer/self/v1/schemas/api/schemas/locations/response/%
./explorer/self/v1/schemas/api/schemas/locations/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/locations/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc
./explorer/self/v1/schemas/api/schemas/locations/rpc/%
./explorer/self/v1/schemas/api/schemas/locations/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc/request
./explorer/self/v1/schemas/api/schemas/locations/rpc/request/%
./explorer/self/v1/schemas/api/schemas/locations/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc/response
./explorer/self/v1/schemas/api/schemas/locations/rpc/response/%
./explorer/self/v1/schemas/api/schemas/locations/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/locations/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/metadata
./explorer/self/v1/schemas/api/schemas/metadata/%
./explorer/self/v1/schemas/api/schemas/metadata/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/metadata/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/metadata/response
./explorer/self/v1/schemas/api/schemas/metadata/response/%
./explorer/self/v1/schemas/api/schemas/metadata/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/metadata/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc
./explorer/self/v1/schemas/api/schemas/metadata/rpc/%
./explorer/self/v1/schemas/api/schemas/metadata/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc/request
./explorer/self/v1/schemas/api/schemas/metadata/rpc/request/%
./explorer/self/v1/schemas/api/schemas/metadata/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc/response
./explorer/self/v1/schemas/api/schemas/metadata/rpc/response/%
./explorer/self/v1/schemas/api/schemas/metadata/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/metadata/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/position
./explorer/self/v1/schemas/api/schemas/position/%
./explorer/self/v1/schemas/api/schemas/position/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/position/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/positions
./explorer/self/v1/schemas/api/schemas/positions/%
./explorer/self/v1/schemas/api/schemas/positions/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/positions/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/positions/response
./explorer/self/v1/schemas/api/schemas/positions/response/%
./explorer/self/v1/schemas/api/schemas/positions/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/positions/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc
./explorer/self/v1/schemas/api/schemas/positions/rpc/%
./explorer/self/v1/schemas/api/schemas/positions/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc/request
./explorer/self/v1/schemas/api/schemas/positions/rpc/request/%
./explorer/self/v1/schemas/api/schemas/positions/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc/response
./explorer/self/v1/schemas/api/schemas/positions/rpc/response/%
./explorer/self/v1/schemas/api/schemas/positions/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/positions/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/search
./explorer/self/v1/schemas/api/schemas/search/%
./explorer/self/v1/schemas/api/schemas/search/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/search/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/search/response
./explorer/self/v1/schemas/api/schemas/search/response/%
./explorer/self/v1/schemas/api/schemas/search/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/search/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc
./explorer/self/v1/schemas/api/schemas/search/rpc/%
./explorer/self/v1/schemas/api/schemas/search/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc/request
./explorer/self/v1/schemas/api/schemas/search/rpc/request/%
./explorer/self/v1/schemas/api/schemas/search/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc/response
./explorer/self/v1/schemas/api/schemas/search/rpc/response/%
./explorer/self/v1/schemas/api/schemas/search/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/search/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/stats
./explorer/self/v1/schemas/api/schemas/stats/%
./explorer/self/v1/schemas/api/schemas/stats/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/stats/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/stats/response
./explorer/self/v1/schemas/api/schemas/stats/response/%
./explorer/self/v1/schemas/api/schemas/stats/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/stats/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc
./explorer/self/v1/schemas/api/schemas/stats/rpc/%
./explorer/self/v1/schemas/api/schemas/stats/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc/request
./explorer/self/v1/schemas/api/schemas/stats/rpc/request/%
./explorer/self/v1/schemas/api/schemas/stats/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc/response
./explorer/self/v1/schemas/api/schemas/stats/rpc/response/%
./explorer/self/v1/schemas/api/schemas/stats/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/stats/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace
./explorer/self/v1/schemas/api/schemas/trace/%
./explorer/self/v1/schemas/api/schemas/trace/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/trace/request
./explorer/self/v1/schemas/api/schemas/trace/request/%
./explorer/self/v1/schemas/api/schemas/trace/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace/response
./explorer/self/v1/schemas/api/schemas/trace/response/%
./explorer/self/v1/schemas/api/schemas/trace/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/response/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc
./explorer/self/v1/schemas/api/schemas/trace/rpc/%
./explorer/self/v1/schemas/api/schemas/trace/rpc/%/directory-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc/%/directory.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc/request
./explorer/self/v1/schemas/api/schemas/trace/rpc/request/%
./explorer/self/v1/schemas/api/schemas/trace/rpc/request/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc/request/%/schema.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc/response
./explorer/self/v1/schemas/api/schemas/trace/rpc/response/%
./explorer/self/v1/schemas/api/schemas/trace/rpc/response/%/schema-html.metapack
./explorer/self/v1/schemas/api/schemas/trace/rpc/response/%/schema.metapack
./explorer/self/v1/schemas/mcp
./explorer/self/v1/schemas/mcp/%
./explorer/self/v1/schemas/mcp/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/%/directory.metapack
./explorer/self/v1/schemas/mcp/error
./explorer/self/v1/schemas/mcp/error/%
./explorer/self/v1/schemas/mcp/error/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/error/%/schema.metapack
./explorer/self/v1/schemas/mcp/initialize
./explorer/self/v1/schemas/mcp/initialize/%
./explorer/self/v1/schemas/mcp/initialize/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/initialize/%/directory.metapack
./explorer/self/v1/schemas/mcp/initialize/request
./explorer/self/v1/schemas/mcp/initialize/request/%
./explorer/self/v1/schemas/mcp/initialize/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/initialize/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/initialize/response
./explorer/self/v1/schemas/mcp/initialize/response/%
./explorer/self/v1/schemas/mcp/initialize/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/initialize/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/notifications
./explorer/self/v1/schemas/mcp/notifications/%
./explorer/self/v1/schemas/mcp/notifications/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/notifications/%/directory.metapack
./explorer/self/v1/schemas/mcp/notifications/cancelled
./explorer/self/v1/schemas/mcp/notifications/cancelled/%
./explorer/self/v1/schemas/mcp/notifications/cancelled/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/notifications/cancelled/%/schema.metapack
./explorer/self/v1/schemas/mcp/notifications/initialized
./explorer/self/v1/schemas/mcp/notifications/initialized/%
./explorer/self/v1/schemas/mcp/notifications/initialized/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/notifications/initialized/%/schema.metapack
./explorer/self/v1/schemas/mcp/ping
./explorer/self/v1/schemas/mcp/ping/%
./explorer/self/v1/schemas/mcp/ping/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/ping/%/directory.metapack
./explorer/self/v1/schemas/mcp/ping/request
./explorer/self/v1/schemas/mcp/ping/request/%
./explorer/self/v1/schemas/mcp/ping/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/ping/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/ping/response
./explorer/self/v1/schemas/mcp/ping/response/%
./explorer/self/v1/schemas/mcp/ping/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/ping/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/request
./explorer/self/v1/schemas/mcp/request/%
./explorer/self/v1/schemas/mcp/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources
./explorer/self/v1/schemas/mcp/resources/%
./explorer/self/v1/schemas/mcp/resources/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/resources/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/list
./explorer/self/v1/schemas/mcp/resources/list/%
./explorer/self/v1/schemas/mcp/resources/list/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/resources/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/list/request
./explorer/self/v1/schemas/mcp/resources/list/request/%
./explorer/self/v1/schemas/mcp/resources/list/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/list/response
./explorer/self/v1/schemas/mcp/resources/list/response/%
./explorer/self/v1/schemas/mcp/resources/list/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/list/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/read
./explorer/self/v1/schemas/mcp/resources/read/%
./explorer/self/v1/schemas/mcp/resources/read/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/resources/read/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/read/request
./explorer/self/v1/schemas/mcp/resources/read/request/%
./explorer/self/v1/schemas/mcp/resources/read/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/read/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/read/response
./explorer/self/v1/schemas/mcp/resources/read/response/%
./explorer/self/v1/schemas/mcp/resources/read/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/read/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/templates
./explorer/self/v1/schemas/mcp/resources/templates/%
./explorer/self/v1/schemas/mcp/resources/templates/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/resources/templates/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list
./explorer/self/v1/schemas/mcp/resources/templates/list/%
./explorer/self/v1/schemas/mcp/resources/templates/list/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/request
./explorer/self/v1/schemas/mcp/resources/templates/list/request/%
./explorer/self/v1/schemas/mcp/resources/templates/list/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/response
./explorer/self/v1/schemas/mcp/resources/templates/list/response/%
./explorer/self/v1/schemas/mcp/resources/templates/list/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/resources/templates/list/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/response
./explorer/self/v1/schemas/mcp/response/%
./explorer/self/v1/schemas/mcp/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools
./explorer/self/v1/schemas/mcp/tools/%
./explorer/self/v1/schemas/mcp/tools/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/tools/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/call
./explorer/self/v1/schemas/mcp/tools/call/%
./explorer/self/v1/schemas/mcp/tools/call/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/tools/call/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/call/request
./explorer/self/v1/schemas/mcp/tools/call/request/%
./explorer/self/v1/schemas/mcp/tools/call/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/tools/call/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/call/response
./explorer/self/v1/schemas/mcp/tools/call/response/%
./explorer/self/v1/schemas/mcp/tools/call/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/tools/call/response/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/list
./explorer/self/v1/schemas/mcp/tools/list/%
./explorer/self/v1/schemas/mcp/tools/list/%/directory-html.metapack
./explorer/self/v1/schemas/mcp/tools/list/%/directory.metapack
./explorer/self/v1/schemas/mcp/tools/list/request
./explorer/self/v1/schemas/mcp/tools/list/request/%
./explorer/self/v1/schemas/mcp/tools/list/request/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/tools/list/request/%/schema.metapack
./explorer/self/v1/schemas/mcp/tools/list/response
./explorer/self/v1/schemas/mcp/tools/list/response/%
./explorer/self/v1/schemas/mcp/tools/list/response/%/schema-html.metapack
./explorer/self/v1/schemas/mcp/tools/list/response/%/schema.metapack
./routes.bin
./schemas
./schemas/example
./schemas/example/foo
./schemas/example/foo/%
./schemas/example/foo/%/blaze-exhaustive.metapack
./schemas/example/foo/%/blaze-fast.metapack
./schemas/example/foo/%/bundle.metapack
./schemas/example/foo/%/dependencies.metapack
./schemas/example/foo/%/dependents.metapack
./schemas/example/foo/%/editor.metapack
./schemas/example/foo/%/health.metapack
./schemas/example/foo/%/locations.metapack
./schemas/example/foo/%/positions.metapack
./schemas/example/foo/%/schema.metapack
./schemas/example/foo/%/stats.metapack
./schemas/self
./schemas/self/v1
./schemas/self/v1/schemas
./schemas/self/v1/schemas/api
./schemas/self/v1/schemas/api/error
./schemas/self/v1/schemas/api/error/%
./schemas/self/v1/schemas/api/error/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/error/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/error/%/bundle.metapack
./schemas/self/v1/schemas/api/error/%/dependencies.metapack
./schemas/self/v1/schemas/api/error/%/dependents.metapack
./schemas/self/v1/schemas/api/error/%/editor.metapack
./schemas/self/v1/schemas/api/error/%/health.metapack
./schemas/self/v1/schemas/api/error/%/locations.metapack
./schemas/self/v1/schemas/api/error/%/positions.metapack
./schemas/self/v1/schemas/api/error/%/schema.metapack
./schemas/self/v1/schemas/api/error/%/stats.metapack
./schemas/self/v1/schemas/api/list
./schemas/self/v1/schemas/api/list/response
./schemas/self/v1/schemas/api/list/response/%
./schemas/self/v1/schemas/api/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/list/response/%/bundle.metapack
./schemas/self/v1/schemas/api/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/list/response/%/dependents.metapack
./schemas/self/v1/schemas/api/list/response/%/editor.metapack
./schemas/self/v1/schemas/api/list/response/%/health.metapack
./schemas/self/v1/schemas/api/list/response/%/locations.metapack
./schemas/self/v1/schemas/api/list/response/%/positions.metapack
./schemas/self/v1/schemas/api/list/response/%/schema.metapack
./schemas/self/v1/schemas/api/list/response/%/stats.metapack
./schemas/self/v1/schemas/api/list/rpc
./schemas/self/v1/schemas/api/list/rpc/request
./schemas/self/v1/schemas/api/list/rpc/request/%
./schemas/self/v1/schemas/api/list/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/list/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/list/rpc/response
./schemas/self/v1/schemas/api/list/rpc/response/%
./schemas/self/v1/schemas/api/list/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/list/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas
./schemas/self/v1/schemas/api/schemas/dependencies
./schemas/self/v1/schemas/api/schemas/dependencies/response
./schemas/self/v1/schemas/api/schemas/dependencies/response/%
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependencies/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependents
./schemas/self/v1/schemas/api/schemas/dependents/response
./schemas/self/v1/schemas/api/schemas/dependents/response/%
./schemas/self/v1/schemas/api/schemas/dependents/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependents/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/dependents/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate
./schemas/self/v1/schemas/api/schemas/evaluate/request
./schemas/self/v1/schemas/api/schemas/evaluate/request/%
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response
./schemas/self/v1/schemas/api/schemas/evaluate/response/%
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/evaluate/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/health
./schemas/self/v1/schemas/api/schemas/health/response
./schemas/self/v1/schemas/api/schemas/health/response/%
./schemas/self/v1/schemas/api/schemas/health/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/health/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc
./schemas/self/v1/schemas/api/schemas/health/rpc/request
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/health/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/locations
./schemas/self/v1/schemas/api/schemas/locations/response
./schemas/self/v1/schemas/api/schemas/locations/response/%
./schemas/self/v1/schemas/api/schemas/locations/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/locations/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc
./schemas/self/v1/schemas/api/schemas/locations/rpc/request
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/locations/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/metadata
./schemas/self/v1/schemas/api/schemas/metadata/response
./schemas/self/v1/schemas/api/schemas/metadata/response/%
./schemas/self/v1/schemas/api/schemas/metadata/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/metadata/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/metadata/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/position
./schemas/self/v1/schemas/api/schemas/position/%
./schemas/self/v1/schemas/api/schemas/position/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/position/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/position/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/position/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/position/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/position/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/position/%/health.metapack
./schemas/self/v1/schemas/api/schemas/position/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/position/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/position/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/position/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/positions
./schemas/self/v1/schemas/api/schemas/positions/response
./schemas/self/v1/schemas/api/schemas/positions/response/%
./schemas/self/v1/schemas/api/schemas/positions/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/positions/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc
./schemas/self/v1/schemas/api/schemas/positions/rpc/request
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/positions/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/search
./schemas/self/v1/schemas/api/schemas/search/response
./schemas/self/v1/schemas/api/schemas/search/response/%
./schemas/self/v1/schemas/api/schemas/search/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/search/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc
./schemas/self/v1/schemas/api/schemas/search/rpc/request
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/search/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/stats
./schemas/self/v1/schemas/api/schemas/stats/response
./schemas/self/v1/schemas/api/schemas/stats/response/%
./schemas/self/v1/schemas/api/schemas/stats/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/stats/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc
./schemas/self/v1/schemas/api/schemas/stats/rpc/request
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/stats/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace
./schemas/self/v1/schemas/api/schemas/trace/request
./schemas/self/v1/schemas/api/schemas/trace/request/%
./schemas/self/v1/schemas/api/schemas/trace/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace/response
./schemas/self/v1/schemas/api/schemas/trace/response/%
./schemas/self/v1/schemas/api/schemas/trace/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/response/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc
./schemas/self/v1/schemas/api/schemas/trace/rpc/request
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/request/%/stats.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/bundle.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/dependencies.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/dependents.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/editor.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/health.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/locations.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/positions.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/schema.metapack
./schemas/self/v1/schemas/api/schemas/trace/rpc/response/%/stats.metapack
./schemas/self/v1/schemas/mcp
./schemas/self/v1/schemas/mcp/error
./schemas/self/v1/schemas/mcp/error/%
./schemas/self/v1/schemas/mcp/error/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/error/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/error/%/bundle.metapack
./schemas/self/v1/schemas/mcp/error/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/error/%/dependents.metapack
./schemas/self/v1/schemas/mcp/error/%/editor.metapack
./schemas/self/v1/schemas/mcp/error/%/health.metapack
./schemas/self/v1/schemas/mcp/error/%/locations.metapack
./schemas/self/v1/schemas/mcp/error/%/positions.metapack
./schemas/self/v1/schemas/mcp/error/%/schema.metapack
./schemas/self/v1/schemas/mcp/error/%/stats.metapack
./schemas/self/v1/schemas/mcp/initialize
./schemas/self/v1/schemas/mcp/initialize/request
./schemas/self/v1/schemas/mcp/initialize/request/%
./schemas/self/v1/schemas/mcp/initialize/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/health.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/initialize/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/initialize/response
./schemas/self/v1/schemas/mcp/initialize/response/%
./schemas/self/v1/schemas/mcp/initialize/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/health.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/initialize/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/notifications
./schemas/self/v1/schemas/mcp/notifications/cancelled
./schemas/self/v1/schemas/mcp/notifications/cancelled/%
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/bundle.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/dependents.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/editor.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/health.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/locations.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/positions.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/schema.metapack
./schemas/self/v1/schemas/mcp/notifications/cancelled/%/stats.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized
./schemas/self/v1/schemas/mcp/notifications/initialized/%
./schemas/self/v1/schemas/mcp/notifications/initialized/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/bundle.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/dependents.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/editor.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/health.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/locations.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/positions.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/schema.metapack
./schemas/self/v1/schemas/mcp/notifications/initialized/%/stats.metapack
./schemas/self/v1/schemas/mcp/ping
./schemas/self/v1/schemas/mcp/ping/request
./schemas/self/v1/schemas/mcp/ping/request/%
./schemas/self/v1/schemas/mcp/ping/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/health.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/ping/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/ping/response
./schemas/self/v1/schemas/mcp/ping/response/%
./schemas/self/v1/schemas/mcp/ping/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/health.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/ping/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/request
./schemas/self/v1/schemas/mcp/request/%
./schemas/self/v1/schemas/mcp/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/request/%/health.metapack
./schemas/self/v1/schemas/mcp/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources
./schemas/self/v1/schemas/mcp/resources/list
./schemas/self/v1/schemas/mcp/resources/list/request
./schemas/self/v1/schemas/mcp/resources/list/request/%
./schemas/self/v1/schemas/mcp/resources/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/list/response
./schemas/self/v1/schemas/mcp/resources/list/response/%
./schemas/self/v1/schemas/mcp/resources/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/list/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/read
./schemas/self/v1/schemas/mcp/resources/read/request
./schemas/self/v1/schemas/mcp/resources/read/request/%
./schemas/self/v1/schemas/mcp/resources/read/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/read/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/read/response
./schemas/self/v1/schemas/mcp/resources/read/response/%
./schemas/self/v1/schemas/mcp/resources/read/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/read/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/templates
./schemas/self/v1/schemas/mcp/resources/templates/list
./schemas/self/v1/schemas/mcp/resources/templates/list/request
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/resources/templates/list/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/response
./schemas/self/v1/schemas/mcp/response/%
./schemas/self/v1/schemas/mcp/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/response/%/health.metapack
./schemas/self/v1/schemas/mcp/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools
./schemas/self/v1/schemas/mcp/tools/call
./schemas/self/v1/schemas/mcp/tools/call/request
./schemas/self/v1/schemas/mcp/tools/call/request/%
./schemas/self/v1/schemas/mcp/tools/call/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/call/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/call/response
./schemas/self/v1/schemas/mcp/tools/call/response/%
./schemas/self/v1/schemas/mcp/tools/call/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/call/response/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/list
./schemas/self/v1/schemas/mcp/tools/list/request
./schemas/self/v1/schemas/mcp/tools/list/request/%
./schemas/self/v1/schemas/mcp/tools/list/request/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/list/request/%/stats.metapack
./schemas/self/v1/schemas/mcp/tools/list/response
./schemas/self/v1/schemas/mcp/tools/list/response/%
./schemas/self/v1/schemas/mcp/tools/list/response/%/blaze-exhaustive.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/blaze-fast.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/bundle.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/dependencies.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/dependents.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/editor.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/health.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/locations.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/positions.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/schema.metapack
./schemas/self/v1/schemas/mcp/tools/list/response/%/stats.metapack
./state.bin
./version.json
EOF

diff "$TMP/manifest.txt" "$TMP/expected.txt"
