#!/bin/sh

set -o errexit
set -o nounset

TMP="$(mktemp -d)"
clean() { rm -rf "$TMP"; }
trap clean EXIT

cat << EOF > "$TMP/one.json"
{
  "url": "https://example.com",
  "html": {},
  "authentication": [
    {
      "type": "jwt",
      "issuer": "https://idp.example.com",
      "name": "test",
      "paths": [ "/test" ],
      "audience": "https://schemas.example.com",
      "algorithms": [ "RS256" ]
    }
  ],
  "contents": {
    "test": {
      "contents": {
        "schemas": {
          "path": "./schemas"
        }
      }
    }
  }
}
EOF

mkdir "$TMP/schemas"

cat << 'EOF' > "$TMP/schemas/test-1.json"
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/test-1",
  "type": "string"
}
EOF

"$1" "$TMP/one.json" "$TMP/output"

cd "$TMP/output"
find . -mindepth 1 \
  \( -path './schemas/self' -o -path './explorer/public/self' \) -prune \
  -o -print \
  | LC_ALL=C sort > "$TMP/manifest.txt"
cd - > /dev/null

cat << 'EOF' > "$TMP/expected.txt"
./authentication.bin
./configuration.json
./explorer
./explorer/public
./explorer/public/%
./explorer/public/%/401.metapack
./explorer/public/%/404.metapack
./explorer/public/%/directory-html.metapack
./explorer/public/%/directory.metapack
./explorer/public/%/login-html.metapack
./explorer/public/%/mcp.metapack
./explorer/public/%/search.metapack
./explorer/public/test
./explorer/public/test/%
./explorer/public/test/%/directory-html.metapack
./explorer/public/test/%/directory.metapack
./explorer/public/test/%/login-html.metapack
./explorer/public/test/schemas
./explorer/public/test/schemas/%
./explorer/public/test/schemas/%/directory-html.metapack
./explorer/public/test/schemas/%/directory.metapack
./explorer/public/test/schemas/%/login-html.metapack
./explorer/public/test/schemas/test-1
./explorer/public/test/schemas/test-1/%
./explorer/public/test/schemas/test-1/%/dependents.metapack
./explorer/public/test/schemas/test-1/%/schema-html.metapack
./explorer/public/test/schemas/test-1/%/schema.metapack
./explorer/test
./explorer/test/%
./explorer/test/%/401.metapack
./explorer/test/%/404.metapack
./explorer/test/%/directory-html.metapack
./explorer/test/%/directory.metapack
./explorer/test/%/login-html.metapack
./explorer/test/%/mcp.metapack
./explorer/test/%/search.metapack
./explorer/test/self
./explorer/test/self/%
./explorer/test/self/%/directory-html.metapack
./explorer/test/self/%/directory.metapack
./explorer/test/self/%/login-html.metapack
./explorer/test/self/v1
./explorer/test/self/v1/%
./explorer/test/self/v1/%/directory-html.metapack
./explorer/test/self/v1/%/directory.metapack
./explorer/test/self/v1/%/login-html.metapack
./explorer/test/self/v1/schemas
./explorer/test/self/v1/schemas/%
./explorer/test/self/v1/schemas/%/directory-html.metapack
./explorer/test/self/v1/schemas/%/directory.metapack
./explorer/test/self/v1/schemas/%/login-html.metapack
./explorer/test/self/v1/schemas/api
./explorer/test/self/v1/schemas/api/%
./explorer/test/self/v1/schemas/api/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/%/directory.metapack
./explorer/test/self/v1/schemas/api/%/login-html.metapack
./explorer/test/self/v1/schemas/api/error
./explorer/test/self/v1/schemas/api/error/%
./explorer/test/self/v1/schemas/api/error/%/dependents.metapack
./explorer/test/self/v1/schemas/api/error/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/error/%/schema.metapack
./explorer/test/self/v1/schemas/api/list
./explorer/test/self/v1/schemas/api/list/%
./explorer/test/self/v1/schemas/api/list/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/list/%/directory.metapack
./explorer/test/self/v1/schemas/api/list/%/login-html.metapack
./explorer/test/self/v1/schemas/api/list/response
./explorer/test/self/v1/schemas/api/list/response/%
./explorer/test/self/v1/schemas/api/list/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/list/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/list/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas
./explorer/test/self/v1/schemas/api/schemas/%
./explorer/test/self/v1/schemas/api/schemas/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies
./explorer/test/self/v1/schemas/api/schemas/dependencies/%
./explorer/test/self/v1/schemas/api/schemas/dependencies/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies/response
./explorer/test/self/v1/schemas/api/schemas/dependencies/response/%
./explorer/test/self/v1/schemas/api/schemas/dependencies/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependencies/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents
./explorer/test/self/v1/schemas/api/schemas/dependents/%
./explorer/test/self/v1/schemas/api/schemas/dependents/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents/response
./explorer/test/self/v1/schemas/api/schemas/dependents/response/%
./explorer/test/self/v1/schemas/api/schemas/dependents/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/dependents/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate
./explorer/test/self/v1/schemas/api/schemas/evaluate/%
./explorer/test/self/v1/schemas/api/schemas/evaluate/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/request
./explorer/test/self/v1/schemas/api/schemas/evaluate/request/%
./explorer/test/self/v1/schemas/api/schemas/evaluate/request/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/request/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/response
./explorer/test/self/v1/schemas/api/schemas/evaluate/response/%
./explorer/test/self/v1/schemas/api/schemas/evaluate/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/evaluate/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/health
./explorer/test/self/v1/schemas/api/schemas/health/%
./explorer/test/self/v1/schemas/api/schemas/health/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/health/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/health/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/health/response
./explorer/test/self/v1/schemas/api/schemas/health/response/%
./explorer/test/self/v1/schemas/api/schemas/health/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/health/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/health/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/locations
./explorer/test/self/v1/schemas/api/schemas/locations/%
./explorer/test/self/v1/schemas/api/schemas/locations/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/locations/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/locations/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/locations/response
./explorer/test/self/v1/schemas/api/schemas/locations/response/%
./explorer/test/self/v1/schemas/api/schemas/locations/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/locations/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/locations/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata
./explorer/test/self/v1/schemas/api/schemas/metadata/%
./explorer/test/self/v1/schemas/api/schemas/metadata/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata/response
./explorer/test/self/v1/schemas/api/schemas/metadata/response/%
./explorer/test/self/v1/schemas/api/schemas/metadata/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/metadata/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/output-error
./explorer/test/self/v1/schemas/api/schemas/output-error/%
./explorer/test/self/v1/schemas/api/schemas/output-error/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/output-error/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/output-error/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/position
./explorer/test/self/v1/schemas/api/schemas/position/%
./explorer/test/self/v1/schemas/api/schemas/position/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/position/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/position/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/positions
./explorer/test/self/v1/schemas/api/schemas/positions/%
./explorer/test/self/v1/schemas/api/schemas/positions/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/positions/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/positions/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/positions/response
./explorer/test/self/v1/schemas/api/schemas/positions/response/%
./explorer/test/self/v1/schemas/api/schemas/positions/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/positions/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/positions/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf
./explorer/test/self/v1/schemas/api/schemas/rdf/%
./explorer/test/self/v1/schemas/api/schemas/rdf/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/request
./explorer/test/self/v1/schemas/api/schemas/rdf/request/%
./explorer/test/self/v1/schemas/api/schemas/rdf/request/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/request/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/response
./explorer/test/self/v1/schemas/api/schemas/rdf/response/%
./explorer/test/self/v1/schemas/api/schemas/rdf/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/rdf/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/search
./explorer/test/self/v1/schemas/api/schemas/search/%
./explorer/test/self/v1/schemas/api/schemas/search/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/search/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/search/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/search/response
./explorer/test/self/v1/schemas/api/schemas/search/response/%
./explorer/test/self/v1/schemas/api/schemas/search/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/search/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/search/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/stats
./explorer/test/self/v1/schemas/api/schemas/stats/%
./explorer/test/self/v1/schemas/api/schemas/stats/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/stats/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/stats/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/stats/response
./explorer/test/self/v1/schemas/api/schemas/stats/response/%
./explorer/test/self/v1/schemas/api/schemas/stats/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/stats/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/stats/response/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/trace
./explorer/test/self/v1/schemas/api/schemas/trace/%
./explorer/test/self/v1/schemas/api/schemas/trace/%/directory-html.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/%/directory.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/%/login-html.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/request
./explorer/test/self/v1/schemas/api/schemas/trace/request/%
./explorer/test/self/v1/schemas/api/schemas/trace/request/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/request/%/schema.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/response
./explorer/test/self/v1/schemas/api/schemas/trace/response/%
./explorer/test/self/v1/schemas/api/schemas/trace/response/%/dependents.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/api/schemas/trace/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp
./explorer/test/self/v1/schemas/mcp/%
./explorer/test/self/v1/schemas/mcp/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/error
./explorer/test/self/v1/schemas/mcp/error/%
./explorer/test/self/v1/schemas/mcp/error/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/error/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/error/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/initialize
./explorer/test/self/v1/schemas/mcp/initialize/%
./explorer/test/self/v1/schemas/mcp/initialize/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/initialize/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/initialize/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/initialize/request
./explorer/test/self/v1/schemas/mcp/initialize/request/%
./explorer/test/self/v1/schemas/mcp/initialize/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/initialize/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/initialize/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/initialize/response
./explorer/test/self/v1/schemas/mcp/initialize/response/%
./explorer/test/self/v1/schemas/mcp/initialize/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/initialize/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/initialize/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/notifications
./explorer/test/self/v1/schemas/mcp/notifications/%
./explorer/test/self/v1/schemas/mcp/notifications/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/notifications/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/notifications/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/notifications/cancelled
./explorer/test/self/v1/schemas/mcp/notifications/cancelled/%
./explorer/test/self/v1/schemas/mcp/notifications/cancelled/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/notifications/cancelled/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/notifications/cancelled/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/notifications/initialized
./explorer/test/self/v1/schemas/mcp/notifications/initialized/%
./explorer/test/self/v1/schemas/mcp/notifications/initialized/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/notifications/initialized/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/notifications/initialized/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/ping
./explorer/test/self/v1/schemas/mcp/ping/%
./explorer/test/self/v1/schemas/mcp/ping/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/ping/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/ping/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/ping/request
./explorer/test/self/v1/schemas/mcp/ping/request/%
./explorer/test/self/v1/schemas/mcp/ping/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/ping/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/ping/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/ping/response
./explorer/test/self/v1/schemas/mcp/ping/response/%
./explorer/test/self/v1/schemas/mcp/ping/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/ping/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/ping/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/prm
./explorer/test/self/v1/schemas/mcp/prm/%
./explorer/test/self/v1/schemas/mcp/prm/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/prm/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/prm/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/prm/response
./explorer/test/self/v1/schemas/mcp/prm/response/%
./explorer/test/self/v1/schemas/mcp/prm/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/prm/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/prm/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/request
./explorer/test/self/v1/schemas/mcp/request/%
./explorer/test/self/v1/schemas/mcp/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources
./explorer/test/self/v1/schemas/mcp/resources/%
./explorer/test/self/v1/schemas/mcp/resources/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/resources/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/list
./explorer/test/self/v1/schemas/mcp/resources/list/%
./explorer/test/self/v1/schemas/mcp/resources/list/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/request
./explorer/test/self/v1/schemas/mcp/resources/list/request/%
./explorer/test/self/v1/schemas/mcp/resources/list/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/response
./explorer/test/self/v1/schemas/mcp/resources/list/response/%
./explorer/test/self/v1/schemas/mcp/resources/list/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/list/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources/read
./explorer/test/self/v1/schemas/mcp/resources/read/%
./explorer/test/self/v1/schemas/mcp/resources/read/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/request
./explorer/test/self/v1/schemas/mcp/resources/read/request/%
./explorer/test/self/v1/schemas/mcp/resources/read/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/response
./explorer/test/self/v1/schemas/mcp/resources/read/response/%
./explorer/test/self/v1/schemas/mcp/resources/read/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/read/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates
./explorer/test/self/v1/schemas/mcp/resources/templates/%
./explorer/test/self/v1/schemas/mcp/resources/templates/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list
./explorer/test/self/v1/schemas/mcp/resources/templates/list/%
./explorer/test/self/v1/schemas/mcp/resources/templates/list/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/request
./explorer/test/self/v1/schemas/mcp/resources/templates/list/request/%
./explorer/test/self/v1/schemas/mcp/resources/templates/list/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/response
./explorer/test/self/v1/schemas/mcp/resources/templates/list/response/%
./explorer/test/self/v1/schemas/mcp/resources/templates/list/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/resources/templates/list/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/response
./explorer/test/self/v1/schemas/mcp/response/%
./explorer/test/self/v1/schemas/mcp/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools
./explorer/test/self/v1/schemas/mcp/tools/%
./explorer/test/self/v1/schemas/mcp/tools/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call
./explorer/test/self/v1/schemas/mcp/tools/call/%
./explorer/test/self/v1/schemas/mcp/tools/call/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/%
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/request
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/response
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/evaluate-schema/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependencies/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-dependents/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-health/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-locations/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-metadata/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-positions/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/request
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/response
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/get-schema-stats/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/%
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/request
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/response
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/instance-to-rdf/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/%
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/request
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/response
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/list-directory/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/request
./explorer/test/self/v1/schemas/mcp/tools/call/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/response
./explorer/test/self/v1/schemas/mcp/tools/call/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/%
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/request
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/response
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/search-schemas/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/%
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/request
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/request/%
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/response
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/response/%
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/call/trace-schema-evaluation/response/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/list
./explorer/test/self/v1/schemas/mcp/tools/list/%
./explorer/test/self/v1/schemas/mcp/tools/list/%/directory-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/%/directory.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/%/login-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/request
./explorer/test/self/v1/schemas/mcp/tools/list/request/%
./explorer/test/self/v1/schemas/mcp/tools/list/request/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/request/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/request/%/schema.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/response
./explorer/test/self/v1/schemas/mcp/tools/list/response/%
./explorer/test/self/v1/schemas/mcp/tools/list/response/%/dependents.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/response/%/schema-html.metapack
./explorer/test/self/v1/schemas/mcp/tools/list/response/%/schema.metapack
./explorer/test/test
./explorer/test/test/%
./explorer/test/test/%/directory-html.metapack
./explorer/test/test/%/directory.metapack
./explorer/test/test/%/login-html.metapack
./explorer/test/test/schemas
./explorer/test/test/schemas/%
./explorer/test/test/schemas/%/directory-html.metapack
./explorer/test/test/schemas/%/directory.metapack
./explorer/test/test/schemas/%/login-html.metapack
./explorer/test/test/schemas/test-1
./explorer/test/test/schemas/test-1/%
./explorer/test/test/schemas/test-1/%/dependents.metapack
./explorer/test/test/schemas/test-1/%/schema-html.metapack
./explorer/test/test/schemas/test-1/%/schema.metapack
./routes.bin
./schemas
./schemas/test
./schemas/test/schemas
./schemas/test/schemas/test-1
./schemas/test/schemas/test-1/%
./schemas/test/schemas/test-1/%/blaze-exhaustive.metapack
./schemas/test/schemas/test-1/%/blaze-fast.metapack
./schemas/test/schemas/test-1/%/bundle.metapack
./schemas/test/schemas/test-1/%/dependencies.metapack
./schemas/test/schemas/test-1/%/editor.metapack
./schemas/test/schemas/test-1/%/health.metapack
./schemas/test/schemas/test-1/%/locations.metapack
./schemas/test/schemas/test-1/%/positions.metapack
./schemas/test/schemas/test-1/%/schema.metapack
./schemas/test/schemas/test-1/%/stats.metapack
./state.bin
./version.json
EOF

diff "$TMP/manifest.txt" "$TMP/expected.txt"
