name: Sandbox
inputs:
  configuration:
    description: Configuration
    required: true
    type: choice
    options:
      - html
      - headless
      - empty
  edition:
    description: Edition
    required: true
    type: choice
    options:
      - community
      - enterprise
  port:
    description: Port
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build Sandbox (${{ inputs.configuration }})
      run: make docker-sandbox-build
      shell: bash
      env:
        SANDBOX_CONFIGURATION: ${{ inputs.configuration }}
        SANDBOX_PORT: ${{ inputs.port }}
        ENTERPRISE: ${{ inputs.edition == 'enterprise' && 'ON' || 'OFF' }}
        PARALLEL: 2
    - name: Up Sandbox (${{ inputs.configuration }})
      run: make docker-sandbox-up
      shell: bash
      env:
        SANDBOX_CONFIGURATION: ${{ inputs.configuration }}
        SANDBOX_PORT: ${{ inputs.port }}
        ENTERPRISE: ${{ inputs.edition == 'enterprise' && 'ON' || 'OFF' }}
    - name: Test Sandbox - E2E (${{ inputs.configuration }})
      run: make test-e2e PRESET=Release
      shell: bash
      env:
        SANDBOX_CONFIGURATION: ${{ inputs.configuration }}
        SANDBOX_PORT: ${{ inputs.port }}
        ENTERPRISE: ${{ inputs.edition == 'enterprise' && 'ON' || 'OFF' }}
        HURL: 'docker run --rm --network=host --volume \$(PWD):/workspace --workdir /workspace ghcr.io/orange-opensource/hurl:7.0.0'
    - name: Test Sandbox - UI (${{ inputs.configuration }})
      run: make test-ui PRESET=Release
      if: inputs.configuration == 'html'
      shell: bash
      env:
        SANDBOX_CONFIGURATION: ${{ inputs.configuration }}
        SANDBOX_PORT: ${{ inputs.port }}
        ENTERPRISE: ${{ inputs.edition == 'enterprise' && 'ON' || 'OFF' }}
    - name: Down Sandbox (${{ inputs.configuration }})
      run: make docker-sandbox-down
      shell: bash
      env:
        SANDBOX_CONFIGURATION: ${{ inputs.configuration }}
        SANDBOX_PORT: ${{ inputs.port }}
        ENTERPRISE: ${{ inputs.edition == 'enterprise' && 'ON' || 'OFF' }}
