if(NOT Core_FOUND)
  set(SOURCEMETA_CORE_INSTALL OFF CACHE BOOL "disable installation")

  if(ONE_TESTS)
    set(SOURCEMETA_CORE_CONTRIB_GOOGLETEST ON CACHE BOOL "GoogleTest")
  else()
    set(SOURCEMETA_CORE_CONTRIB_GOOGLETEST OFF CACHE BOOL "GoogleTest")
  endif()

  if(ONE_ENTERPRISE)
    set(SOURCEMETA_CORE_CRYPTO_USE_SYSTEM_OPENSSL ON CACHE BOOL "Enable OpenSSL")
  endif()

  set(SOURCEMETA_CORE_CONTRIB_GOOGLEBENCHMARK OFF CACHE BOOL "GoogleBenchmark")

  set(SOURCEMETA_CORE_LANG_PROCESS OFF CACHE BOOL "Process")
  set(SOURCEMETA_CORE_JSONL OFF CACHE BOOL "JSONL")

  add_subdirectory("${PROJECT_SOURCE_DIR}/vendor/core")
  include(Sourcemeta)
  set(Core_FOUND ON)
endif()
