name: E2E
inputs:
  path:
    description: Path to the e2e test suite
    required: true
  edition:
    description: Edition
    required: true

runs:
  using: 'composite'
  steps:
    # Work around BuildKit snapshot corruption on GitHub Actions runners
    - name: Prune BuildKit cache (${{ inputs.path }})
      run: docker builder prune --all --force
      shell: bash

    - name: E2E (${{ inputs.path }})
      run: >
        make -C ${{ inputs.path }}
        EDITION=${{ inputs.edition }}
        HURL='docker run --rm --network=host --volume $$(pwd):/workspace --workdir /workspace ghcr.io/orange-opensource/hurl:8.0.1'
      shell: bash
